#!/usr/bin/env bash
#
# Carltine setup.
#
# Goal: working router on localhost with zero third-party accounts, then a
# checklist for the optional pieces. The free tier needs no signup, no card,
# and no account anywhere, because the router never touches your tokens.
#
#   ./scripts/setup.sh          # local only
#   ./scripts/setup.sh --d1     # also provision Cloudflare D1 (needs an account)
#
set -euo pipefail

BOLD=$'\033[1m'; DIM=$'\033[2m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; RED=$'\033[31m'; RESET=$'\033[0m'
ok()   { printf '%s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
warn() { printf '%s!%s %s\n' "$YELLOW" "$RESET" "$1"; }
die()  { printf '%sx%s %s\n' "$RED" "$RESET" "$1" >&2; exit 1; }
step() { printf '\n%s==>%s %s%s%s\n' "$BOLD" "$RESET" "$BOLD" "$1" "$RESET"; }

cd "$(dirname "$0")/.."
WANT_D1=false
[[ "${1:-}" == "--d1" ]] && WANT_D1=true

command -v node >/dev/null || die "node is required (24 or newer)."

step "Checking Node"
NODE_MAJOR=$(node -p "process.versions.node.split('.')[0]")
if (( NODE_MAJOR < 22 )); then
  die "Node ${NODE_MAJOR} is too old. Carltine needs 22+ (24 recommended)."
fi
ok "node $(node -v)"

step "Installing dependencies"
if [[ -d node_modules ]] && [[ -f package-lock.json ]]; then
  ok "dependencies already installed (delete node_modules to reinstall)"
else
  npm install --silent
  ok "installed"
fi

step "Generating a signing secret"
# One branch, not two. The old `if -f / elif grep` shape could never take the
# elif, because grep only runs when the file is absent.
if [[ -f .env.local ]] && grep -qE '^CARLTINE_INGEST_SECRET=.{16,}' .env.local; then
  ok "secret already present in .env.local"
else
  if [[ -f .env.local ]]; then
    cp .env.local .env.local.bak
    warn ".env.local had no usable secret; backed up to .env.local.bak"
  fi
  SECRET=$(node -e "console.log(require('node:crypto').randomBytes(32).toString('hex'))")
  cat > .env.local <<EOF
# Generated by scripts/setup.sh
CARLTINE_INGEST_SECRET=${SECRET}
CARLTINE_FREE_DAILY_LIMIT=5000

# Optional: add provider keys to get real completions instead of simulated ones.
# OPENAI_API_KEY=
# ANTHROPIC_API_KEY=
# GOOGLE_API_KEY=
# DEEPSEEK_API_KEY=
# QWEN_API_KEY=
# MISTRAL_API_KEY=

# Optional: Cloudflare D1 (see --d1)
# CARLTINE_D1_ACCOUNT_ID=
# CARLTINE_D1_DATABASE_ID=
# CARLTINE_CF_API_TOKEN=
EOF
  ok "wrote .env.local with a fresh secret"
fi

step "Seeding the ledger with sample records"
if npm run seed --silent 2>&1 | tail -3; then
  ok "chain seeded"
else
  warn "seeding skipped (chain may already exist)"
fi

# The setup script used to declare success without ever reading the chain back.
# That is how a signing-key mismatch shipped: the seed and the dev server were
# using different keys, so every record failed verification, and nothing here
# noticed. Verifying now means a broken install fails loudly at setup instead of
# quietly on the user's first visit to the ledger.
step "Verifying the chain"
if npm run verify --silent; then
  ok "chain verifies against this instance's secret"
else
  die "chain does NOT verify (see above). Remove .carltine/ and re-run ./scripts/setup.sh"
fi

if [[ "$WANT_D1" == true ]]; then
  step "Provisioning Cloudflare D1"
  command -v npx >/dev/null || die "npx is required"
  npx wrangler whoami >/dev/null 2>&1 || die "Not logged in to Cloudflare. Run 'npx wrangler login' first."
  ok "authenticated"

  DB_NAME="carltine"
  if npx wrangler d1 list 2>/dev/null | grep -q "$DB_NAME"; then
    warn "database '$DB_NAME' already exists, reusing it"
  else
    npx wrangler d1 create "$DB_NAME"
    ok "created $DB_NAME"
  fi

  npx wrangler d1 execute "$DB_NAME" --file=db/schema.sql
  ok "schema applied"

  warn "Two values still need to be added to .env.local by hand:"
  printf '    CARLTINE_D1_ACCOUNT_ID   (from the create output above)\n'
  printf '    CARLTINE_D1_DATABASE_ID  (from the create output above)\n'
  printf '    CARLTINE_CF_API_TOKEN    (Cloudflare dashboard -> API Tokens -> D1 Edit)\n'
fi

step "Verifying the router"
# Via the package script, not `npx tsx ... --silent`. `--silent` is an npm flag,
# not a tsx one, so passing it to tsx forwarded an unknown argument; the run
# aborted with SIGABRT inside this script while working fine standalone, which
# is a miserable thing to hand someone as their first run.
if npm run test:router --silent; then
  ok "routing checks passed"
else
  die "routing checks failed"
fi

step "Verifying tamper detection"
if npm run test:chain --silent; then
  ok "tamper-detection checks passed"
else
  die "tamper-detection checks failed. The core claim of this product is that edits are caught;
   if that is failing there is no point continuing."
fi

step "Ready"
printf '  %sStart the server:%s  npm run dev\n' "$BOLD" "$RESET"
printf '  %sThen open:%s          http://localhost:3000\n' "$BOLD" "$RESET"
printf '  %sPlayground:%s         http://localhost:3000/app/playground\n' "$BOLD" "$RESET"
printf '  %sLedger:%s             http://localhost:3000/app\n' "$BOLD" "$RESET"
cat <<'EOF'

  Without a provider key the router returns simulated responses, clearly
  labelled as such. Add any provider key to .env.local and restart to get
  real completions. Nothing else is required: no account, no card, no signup.
EOF
