/**
 * Setup regression test.
 *
 * Guards the worst bug this project has had. `npm run seed` runs under tsx,
 * which does not read .env.local, while the Next.js dev server does. The seed
 * therefore signed records with a generated fallback key and the server
 * verified them with CARLTINE_INGEST_SECRET from .env.local. Every seeded
 * record failed its signature check, so a brand new user following the
 * quickstart opened the ledger to "record 0 was not signed by this ingest
 * service" on their first ever run.
 *
 * Nothing caught it: typecheck passed, lint passed, the build passed, and the
 * unit tests passed, because each of them only ever ran one process. It takes
 * two processes with disagreeing environments to reproduce, which is exactly
 * the case no existing test covered.
 *
 * So this test creates a throwaway project directory with its own .env.local,
 * runs the real seed against it in a child process, then verifies the chain
 * from a second child process using only what is on disk. If the two ever
 * disagree about the secret again, this fails.
 */
import { execFileSync } from "node:child_process";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, cpSync, symlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

const ROOT = process.cwd();
let failures = 0;
let checks = 0;

function check(name: string, passed: boolean, detail = ""): void {
  checks++;
  if (passed) {
    console.log(`  ok  ${name}`);
  } else {
    failures++;
    console.error(`FAIL  ${name}${detail ? `\n      ${detail}` : ""}`);
  }
}

/** Run a snippet in a fresh process rooted at `dir`, with a clean environment. */
function runIn(
  dir: string,
  snippet: string,
): { ok: boolean; stdout: string; stderr: string } {
  // Use the project's own tsx rather than npx, so the child cannot download a
  // different version mid-test.
  const tsx = path.join(ROOT, "node_modules", ".bin", "tsx");
  try {
    const stdout = execFileSync(tsx, ["-e", snippet], {
      cwd: dir,
      encoding: "utf8",
      // Deliberately minimal: nothing that could carry a signing secret in
      // from this process. The child has to resolve it from .env.local, which
      // is the entire behaviour under test.
      env: {
        PATH: process.env.PATH ?? "",
        HOME: process.env.HOME ?? "",
        NODE_ENV: "test",
      },
      stdio: ["ignore", "pipe", "pipe"],
    });
    return { ok: true, stdout, stderr: "" };
  } catch (err) {
    const e = err as { stdout?: string; stderr?: string };
    return { ok: false, stdout: e.stdout ?? "", stderr: e.stderr ?? String(err) };
  }
}

const workdir = mkdtempSync(path.join(tmpdir(), "carltine-setup-"));

try {
  // A minimal project: the lib sources, the scripts, and a .env.local holding
  // the secret exactly as scripts/setup.sh writes it. node_modules is
  // symlinked rather than copied so the child resolves imports the same way
  // it would in a real clone, without a 200MB copy per test run.
  mkdirSync(path.join(workdir, "scripts"), { recursive: true });
  cpSync(path.join(ROOT, "src"), path.join(workdir, "src"), { recursive: true });
  for (const f of ["load-env.ts", "seed.ts", "verify.ts"]) {
    cpSync(path.join(ROOT, "scripts", f), path.join(workdir, "scripts", f));
  }
  cpSync(path.join(ROOT, "tsconfig.json"), path.join(workdir, "tsconfig.json"));
  symlinkSync(path.join(ROOT, "node_modules"), path.join(workdir, "node_modules"), "dir");
  writeFileSync(
    path.join(workdir, ".env.local"),
    "# Generated by scripts/setup.sh\nCARLTINE_INGEST_SECRET=" +
      "a".repeat(64) +
      "\nCARLTINE_FREE_DAILY_LIMIT=5000\n",
  );

  console.log("\nSetup regression: does the seed agree with the running app?\n");

  // 1. Seeding, in its own process, with no CARLTINE_INGEST_SECRET in the
  //    environment. It has to come from .env.local or this breaks.
  //
  //    The child prints its own view of the secret so the assertion is on what
  //    the seed actually resolved, not on a side effect like a key file
  //    appearing. An earlier version inferred that from the absence of
  //    .carltine/dev-ingest-secret and could be satisfied by accident.
  const seed = runIn(
    workdir,
    'import { isEphemeralSigning } from "./src/lib/sign"; import "./scripts/seed"; console.log("SEED_EPHEMERAL=" + isEphemeralSigning());',
  );
  check("seed runs in a clean environment", seed.ok, seed.stderr.slice(0, 400));
  check(
    "the seed resolved CARLTINE_INGEST_SECRET from .env.local",
    /SEED_EPHEMERAL=false/.test(seed.stdout),
    `seed reported ${seed.stdout.match(/SEED_EPHEMERAL=\w+/)?.[0] ?? "nothing"}; ` +
      "if this is true the seed ignored .env.local, which is the original bug",
  );

  // 2. Verification, in a second process, always loading .env.local. This
  //    stands in for the Next.js server, which reads .env.local and therefore
  //    always verifies against the real secret.
  //
  //    Loading it here explicitly matters. An earlier version of this test
  //    imported only the store, so the verify process fell back to the same
  //    generated dev key the seed had used, both sides agreed, and the test
  //    passed even with the fix removed. It was checking that a key can sign
  //    its own work, which was never the thing that broke.
  const verify = runIn(
    workdir,
    'import { isEphemeralSigning } from "./src/lib/sign"; import "./scripts/load-env"; import { verifyChain } from "./src/lib/store"; verifyChain().then((r) => { console.log("VERIFY_EPHEMERAL=" + isEphemeralSigning()); console.log(JSON.stringify(r)); });',
  );
  check("verify runs in a clean environment", verify.ok, verify.stderr.slice(0, 400));
  check(
    "the verifying process resolved the same secret from .env.local",
    /VERIFY_EPHEMERAL=false/.test(verify.stdout),
    "the verifying process fell back to a dev key, so it is not modelling the app",
  );

  let parsed: { valid?: boolean; length?: number; reason?: string | null } = {};
  try {
    // The last line is the JSON; the one before it is the ephemeral marker.
    const jsonLine = verify.stdout
      .trim()
      .split("\n")
      .filter((l) => l.trim().startsWith("{"))
      .pop();
    parsed = JSON.parse(jsonLine ?? "{}");
  } catch {
    // handled by the assertion below
  }

  check(
    "records seeded from .env.local verify against the same secret",
    parsed.valid === true,
    `chain reported valid=${parsed.valid} reason=${parsed.reason ?? "n/a"}`,
  );
  check(
    "chain is non-empty (the seed actually wrote something)",
    (parsed.length ?? 0) > 0,
    `length=${parsed.length ?? 0}`,
  );
} finally {
  rmSync(workdir, { recursive: true, force: true });
}

console.log(
  failures === 0
    ? `\nAll ${checks} setup regression checks passed.\n`
    : `\n${failures} of ${checks} setup regression checks FAILED.\n`,
);
process.exit(failures === 0 ? 0 : 1);
